table Dim_Calendario
	lineageTag: dcbb3008-9048-4685-8e2f-d693b9bf677c

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 636d9e58-8407-4b15-b45b-4e91a0988cc1
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 47632e79-9f2e-475d-85a5-f5ffb395a9f3
			defaultHierarchy: LocalDateTable_e55619c2-ca79-4564-8a91-418cf46920a0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: a17aa832-337b-4f1f-8c46-d9f66bc8a86c
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 16790030-17fe-4d4f-9b42-46aec2557574
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: a2ac13e8-d3c7-49cc-b4e3-19df8f03b227
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: d91c2cc0-19af-456c-9be4-1d9ef1f9de63
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: cb3a3742-1060-4dca-a0f4-605fd168c471
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\diego\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

